### ISSUE TITLE
Watchman Error

### ISSUE THREAD

**Issue by kginger** [bryanheinz/watchman_plugins#2]
New installations of v.3.0.2.122 I get this error in Watchman:

Error, can't find the CloudBerry Backup configuration folder.

<img width="845" alt="Screen Shot 2020-09-10 at 5 39 18 PM" src="https://user-images.githubusercontent.com/18317658/92832628-c0923600-f38c-11ea-9742-1e80aa7de270.png">

<img width="909" alt="Screen Shot 2020-09-10 at 5 51 58 PM" src="https://user-images.githubusercontent.com/18317658/92834115-80cc4e00-f38e-11ea-8abf-396778f4acab.png">

**Comment by bryanheinz** [comment]
Oh hey, I made a bad assumption! Every install I've done of CBB 2.10-3.0 has yielded `/Library/Application Support/Online Backup/00000000-0000-0000-0000-000000000000` as the config path. I'll see if I can do a quick fix for that this afternoon.

@kginger what version of CBB did you install and how did you install it?

**Comment by bryanheinz** [comment]
@kginger i just pushed a potential fix. this should remove the assumption that a config folder name will contain all zeros. let me know if that works for you here or on Slack.

**Comment by bryanheinz** [comment]
i'm closing this out, but if anyone is still having issues with this please let me know.
